### ISSUE TITLE
RuntimeError: populate() isn't reentrant

### ISSUE THREAD

**Issue by Lunatic666** [jkbrzt/cointrol#1]
I'm trying to make the Cointrol work on a Raspberry PI 2. I'm following the instructions from the README until ```cointrol/manage.py syncdb --noinput```, which gives me an error: https://gist.github.com/Lunatic666/093f09a614ad8bbd16d6

I'm executing everything as non-root user on a Python 3.4.3 environment

**Comment by jkbrzt** [comment]
Strange, I'm unable to reproduce this. Just tried following the instruction on my Mac again and everything works fine for me.

**Comment by Lunatic666** [comment]
Yes, it must be the Raspberry PI Python, I tried it on a CentOS box, everything works fine there...

**Comment by jkbrzt** [comment]
Ok, good luck with that :+1: Feel free to re-open.
